import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Download, FileText, Github, Link, Loader2, Plus, Trash2, Upload, Users, X } from 'lucide-react';
import { coeApi, membersApi } from '@/lib/api';
import { cn } from '@/lib/utils';
import { useAuth } from '@/context/AuthContext';

type Member = { id: string; name: string; designation?: string | null };
type Milestone = { id: string; title: string; description?: string | null; completed: boolean; updates: Array<{ id: string; body: string }> };
type Asset = { id: string; kind: 'LINK' | 'FILE'; label: string; url?: string | null; fileName?: string | null };
type LearningProject = { id: string; title: string; description?: string | null; createdById: string; members: Array<{ memberId: string; member: Member }>; milestones: Milestone[]; assets: Asset[] };

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/45 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-border bg-card shadow-2xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 className="font-semibold text-foreground">{title}</h2><button onClick={onClose} className="text-muted-foreground hover:text-foreground"><X className="h-5 w-5" /></button></div>{children}</div></div>;
}

export default function LearningProjects() {
  const { user, hasPermission } = useAuth();
  const isAdmin = hasPermission('manageTeam');
  const queryClient = useQueryClient();
  const [creating, setCreating] = useState(false);
  const [selected, setSelected] = useState<LearningProject | null>(null);
  const [error, setError] = useState('');
  const { data, isLoading } = useQuery<{ projects: LearningProject[] }>({ queryKey: ['coe-learning-projects'], queryFn: () => coeApi.learningProjects().then(result => result.data) });
  const projects = data?.projects || [];
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['coe-learning-projects'] });
  const canEdit = (project: LearningProject) => isAdmin || project.createdById === user?.id || project.members.some(item => item.memberId === user?.teamMemberId);

  return <section className="space-y-5">
    <div className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-foreground">Learning Projects</h2><p className="mt-1 text-sm text-muted-foreground">Build learning projects with teammates, milestones, progress updates, GitHub links and shared files.</p></div><button onClick={() => setCreating(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" /> New learning project</button></div>
    {error && <p className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}
    {isLoading ? <Loader2 className="mx-auto my-12 h-5 w-5 animate-spin text-muted-foreground" /> : projects.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">No learning projects yet. Start one with teammates and set the first milestone.</div> : <div className="grid gap-4 lg:grid-cols-2">{projects.map(project => { const complete = project.milestones.filter(item => item.completed).length; const progress = project.milestones.length ? Math.round(complete / project.milestones.length * 100) : 0; return <button key={project.id} onClick={() => setSelected(project)} className="rounded-2xl border border-border bg-card p-5 text-left shadow-sm transition hover:border-primary/35 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><h3 className="text-base font-semibold text-foreground">{project.title}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{project.description || 'No description added.'}</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">{progress}%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} /></div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{complete}/{project.milestones.length} milestones complete</span><span className="inline-flex items-center gap-1"><Users className="h-3.5 w-3.5" /> {project.members.length}</span></div></button>; })}</div>}
    {creating && <CreateProjectModal onClose={() => setCreating(false)} onSuccess={() => { setCreating(false); refresh(); }} onError={setError} />}
    {selected && <ProjectDetail project={selected} canEdit={canEdit(selected)} isAdmin={isAdmin} onClose={() => setSelected(null)} onChanged={() => { refresh(); setSelected(null); }} onError={setError} />}
  </section>;
}

function CreateProjectModal({ onClose, onSuccess, onError }: { onClose: () => void; onSuccess: () => void; onError: (message: string) => void }) {
  const [loading, setLoading] = useState(false); const [memberIds, setMemberIds] = useState<string[]>([]);
  const members = useQuery<{ data: Member[] }>({ queryKey: ['members-all'], queryFn: () => membersApi.list({ limit: 1000 }).then(result => result.data) }).data?.data || [];
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); try { await coeApi.createLearningProject({ title: form.get('title'), description: form.get('description'), memberIds }); onSuccess(); } catch (error) { onError(error instanceof Error ? error.message : 'Could not create the learning project'); } finally { setLoading(false); } }
  return <Modal title="New learning project" onClose={onClose}><form onSubmit={submit} className="space-y-4 p-5"><label className="block text-sm font-medium text-foreground">Project title<input required name="title" className="input mt-1 w-full" placeholder="e.g. Build a data pipeline" /></label><label className="block text-sm font-medium text-foreground">Description<textarea name="description" rows={4} className="input mt-1 w-full resize-y" placeholder="What will the team learn and build?" /></label><div><p className="text-sm font-medium text-foreground">Teammates</p><div className="mt-2 grid max-h-40 gap-1 overflow-y-auto rounded-xl border border-border p-2 sm:grid-cols-2">{members.map(member => <label key={member.id} className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-sm hover:bg-secondary"><input type="checkbox" checked={memberIds.includes(member.id)} onChange={event => setMemberIds(event.target.checked ? [...memberIds, member.id] : memberIds.filter(id => id !== member.id))} /><span>{member.name}</span></label>)}</div></div><div className="flex justify-end gap-2 border-t border-border pt-4"><button type="button" onClick={onClose} className="rounded-xl border border-border px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={loading} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{loading ? 'Creating…' : 'Create project'}</button></div></form></Modal>;
}

function ProjectDetail({ project, canEdit, isAdmin, onClose, onChanged, onError }: { project: LearningProject; canEdit: boolean; isAdmin: boolean; onClose: () => void; onChanged: () => void; onError: (message: string) => void }) {
  const [title, setTitle] = useState(project.title); const [description, setDescription] = useState(project.description || ''); const [milestone, setMilestone] = useState(''); const [updateFor, setUpdateFor] = useState<string | null>(null); const [update, setUpdate] = useState(''); const [linkUrl, setLinkUrl] = useState(''); const [file, setFile] = useState<File | null>(null); const [memberId, setMemberId] = useState('');
  const members = useQuery<{ data: Member[] }>({ queryKey: ['members-all'], queryFn: () => membersApi.list({ limit: 1000 }).then(result => result.data) }).data?.data || [];
  const complete = project.milestones.filter(item => item.completed).length; const progress = project.milestones.length ? Math.round(complete / project.milestones.length * 100) : 0;
  async function run(action: () => Promise<unknown>) { try { await action(); onChanged(); } catch (error) { onError(error instanceof Error ? error.message : 'Could not save changes'); } }
  const deleteProject = () => { if (window.confirm(`Delete ${project.title}? This cannot be undone.`)) void run(() => coeApi.deleteLearningProject(project.id)); };
  const addLink = () => { const url = linkUrl.trim(); if (!url) return; const label = url.replace(/^https?:\/\/(www\.)?/, '').split('/')[0] || 'Project link'; void run(() => coeApi.addLearningProjectLink(project.id, { label, url })); };
  const uploadFile = () => { if (!file) return; const form = new FormData(); form.append('file', file); void run(() => coeApi.uploadLearningProjectFile(project.id, form)); };

  return <Modal title={project.title} onClose={onClose}><div className="space-y-5 p-5">
    {canEdit ? <div className="space-y-3 rounded-xl border border-border bg-secondary/30 p-3"><input value={title} onChange={event => setTitle(event.target.value)} className="input w-full text-sm font-semibold" placeholder="Project title" /><textarea value={description} onChange={event => setDescription(event.target.value)} rows={3} className="input w-full resize-y text-sm" placeholder="Project description" /><div className="flex justify-end gap-2">{isAdmin && <button onClick={deleteProject} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-50">Delete project</button>}<button disabled={!title.trim()} onClick={() => run(() => coeApi.updateLearningProject(project.id, { title: title.trim(), description: description.trim() || null }))} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50">Save changes</button></div></div> : <p className="whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{project.description || 'No description added.'}</p>}
    <div><div className="mb-1 flex justify-between text-sm font-semibold text-foreground"><span>Milestone progress</span><span>{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full bg-primary" style={{ width: `${progress}%` }} /></div><p className="mt-1 text-xs text-muted-foreground">{complete} of {project.milestones.length} milestones complete</p></div>
    <div><h3 className="mb-2 font-semibold text-foreground">Milestones</h3><div className="space-y-2">{project.milestones.map(item => <div key={item.id} className="rounded-xl border border-border p-3"><div className="flex gap-2"><input disabled={!canEdit} type="checkbox" checked={item.completed} onChange={event => void run(() => coeApi.updateLearningProjectMilestone(project.id, item.id, { completed: event.target.checked }))} className="mt-1 h-4 w-4 accent-primary" /><div className="min-w-0 flex-1"><p className={cn('text-sm font-semibold', item.completed && 'text-muted-foreground line-through')}>{item.title}</p>{item.description && <p className="text-xs text-muted-foreground">{item.description}</p>}</div>{canEdit && <button onClick={() => void run(() => coeApi.deleteLearningProjectMilestone(project.id, item.id))} className="text-muted-foreground hover:text-rose-600"><Trash2 className="h-4 w-4" /></button>}</div>{item.updates.map(note => <p key={note.id} className="mt-2 rounded-lg bg-secondary/60 px-2.5 py-2 text-xs text-foreground">{note.body}</p>)}{canEdit && <div className="mt-2 flex gap-2"><input value={updateFor === item.id ? update : ''} onFocus={() => setUpdateFor(item.id)} onChange={event => { setUpdateFor(item.id); setUpdate(event.target.value); }} className="input h-8 flex-1 text-xs" placeholder="What did you complete?" /><button onClick={() => { if (update.trim()) void run(() => coeApi.addLearningProjectUpdate(project.id, item.id, update.trim())); }} className="rounded-lg border border-border px-2 text-xs font-semibold">Add</button></div>}</div>)}</div>{canEdit && <div className="mt-2 flex gap-2"><input value={milestone} onChange={event => setMilestone(event.target.value)} className="input h-9 flex-1 text-sm" placeholder="Add a milestone" /><button onClick={() => { if (milestone.trim()) void run(() => coeApi.addLearningProjectMilestone(project.id, { title: milestone.trim() })); }} className="rounded-lg bg-primary px-3 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" /></button></div>}</div>
    <div><h3 className="mb-2 font-semibold text-foreground">Project work</h3><div className="space-y-2">{project.assets.map(asset => <div key={asset.id} className="flex items-center gap-2 rounded-xl border border-border p-2.5"><FileText className="h-4 w-4 text-primary" /><span className="min-w-0 flex-1 truncate text-sm">{asset.label}</span>{asset.kind === 'LINK' ? <a href={asset.url || '#'} target="_blank" rel="noreferrer" className="text-primary"><Link className="h-4 w-4" /></a> : <button onClick={() => void run(async () => { const data = (await coeApi.getLearningProjectFile(project.id, asset.id)).data; window.open(data.downloadUrl, '_blank', 'noopener,noreferrer'); })} className="text-primary"><Download className="h-4 w-4" /></button>}{canEdit && <button onClick={() => void run(() => coeApi.deleteLearningProjectAsset(project.id, asset.id))} className="text-muted-foreground hover:text-rose-600"><Trash2 className="h-4 w-4" /></button>}</div>)}</div>{canEdit && <div className="mt-2 grid gap-2 sm:grid-cols-2"><div className="flex gap-1"><input value={linkUrl} onChange={event => setLinkUrl(event.target.value)} className="input h-9 min-w-0 flex-1 text-xs" placeholder="GitHub or project link" /><button onClick={addLink} className="rounded-lg border border-border px-2"><Github className="h-4 w-4" /></button></div><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-semibold"><Upload className="h-4 w-4" />{file?.name || 'Upload ZIP or document'}<input type="file" className="hidden" onChange={event => setFile(event.target.files?.[0] || null)} /></label>{file && <button onClick={uploadFile} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">Upload</button>}</div>}</div>
    <div><h3 className="mb-2 font-semibold text-foreground">Teammates</h3><div className="flex flex-wrap gap-2">{project.members.map(item => <span key={item.memberId} className="rounded-full bg-secondary px-2.5 py-1 text-xs text-foreground">{item.member.name}{canEdit && <button onClick={() => void run(() => coeApi.removeLearningProjectMember(project.id, item.memberId))} className="ml-1 text-muted-foreground">×</button>}</span>)}</div>{canEdit && <div className="mt-2 flex gap-2"><select value={memberId} onChange={event => setMemberId(event.target.value)} className="input h-9 flex-1 text-sm"><option value="">Add teammate…</option>{members.filter(member => !project.members.some(item => item.memberId === member.id)).map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select><button onClick={() => { if (memberId) void run(() => coeApi.addLearningProjectMember(project.id, memberId)); }} className="rounded-lg border border-border px-3 text-sm font-semibold">Add</button></div>}</div>
  </div></Modal>;
}
